[project]
name = "puddle-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.12.14",
    "discord-py>=2.5.2",
    "psycopg[binary]>=3.1.0",
    "python-dotenv>=1.0.0",
]
